spring:

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO_METHOD}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH}
          starttls:
            enable: ${SMTP_STARTTLS}

grabit:
  logo:

monitor:
#  Failed sales cron
  enabled: ${FAILED_SALES_MONITOR_ENABLED}
  cron: ${FAILED_SALES_MONITOR_CRON} # every 5 minutes
  windowSize: ${FAILED_SALES_MONITOR_WINDOW_SIZE}
  failureThreshold: ${FAILED_SALES_MONITOR_FAILURE_THRESHOLD}
  alertCooldownMinutes: ${FAILED_SALES_MONITOR_ALERT_COOLDOWN_MINUTES}
  slidingWindowSize: ${FAILED_SALES_MONITOR_SLIDING_WINDOW_SIZE}
  slidingFailureThreshold: ${FAILED_SALES_MONITOR_SLIDING_FAILURE_THRESHOLD}

#  baseline monitor
  baselineEnabled: ${BASELINE_MONITOR_ENABLED}
  baselineCron: ${BASELINE_MONITOR_CRON}
  lookback-period-months: ${BASELINE_MONITOR_LOOKBACK_PERIOD_MONTHS}

#  Sales report configuration
  reportEnabled:
  reportCron:
  reportWindowHours:
  reportBaselineHours:

#  Hourly sales baseline computation


cbl-monitor:
  enabled: true
  cron: 0 0 * * * *

