spring:

  datasource:
    url: jdbc:mysql://localhost:3306/vm_alert_service
    username: root
    password: madushan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: cba.wireme@gmail.com
    password: tdahitvmbpexfkpd
#    username: sltclog2119@gmail.com
#    password: sacvdhoycreovxpy
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

grabit:
  logo:

monitor:
#  SALE FAILED monitoring
  enabled: true
  cron: "0 */5 * * * *" # every 5 minutes
  windowSize: 10
  failureThreshold: 3
  alertCooldownMinutes: 60
  slidingWindowSize: 10
  slidingFailureThreshold: 5

#  HOURLY SALES BASELINE COMPUTATION
  baselineEnabled: true
  baselineCron: "0 30 2 * * *"
  lookback-period-months: 1

#  SALES ALERT configuration
  reportEnabled: true
  reportCron: "0 0 * * * *"
  reportWindowHours: 1
  reportBaselineHours: 24

#  Hourly sales baseline computation
  hourlyBaselineAlertEnabled: true
  hourlyBaselineAlertCron: "0 5 * * * *"
  baselineDropThresholdPercent: 0.30
  baselineConsecutiveHoursRequired: 2

cbl-monitor:
  enabled: true
  cron: 0 0 * * * *
